// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJYiesSAAnSLBEnexcLNm4EhHLmer_s0',
    appId: '1:401547607741:web:f087967949c98e524141d4',
    messagingSenderId: '401547607741',
    projectId: 'todo-9b83f',
    authDomain: 'todo-9b83f.firebaseapp.com',
    storageBucket: 'todo-9b83f.appspot.com',
    measurementId: 'G-JW1VC92Y06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsN-33QIu86uazVDHbmbLVPf_opOXlFLg',
    appId: '1:401547607741:android:60802c5de28087594141d4',
    messagingSenderId: '401547607741',
    projectId: 'todo-9b83f',
    storageBucket: 'todo-9b83f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCePd_J6esf3AQ33WG2TUY61BTBEvP6vIY',
    appId: '1:401547607741:ios:7e4145b84149f91d4141d4',
    messagingSenderId: '401547607741',
    projectId: 'todo-9b83f',
    storageBucket: 'todo-9b83f.appspot.com',
    iosClientId: '401547607741-qu61qujcs13j4sonhjosopvh8rskke8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCePd_J6esf3AQ33WG2TUY61BTBEvP6vIY',
    appId: '1:401547607741:ios:7e4145b84149f91d4141d4',
    messagingSenderId: '401547607741',
    projectId: 'todo-9b83f',
    storageBucket: 'todo-9b83f.appspot.com',
    iosClientId: '401547607741-qu61qujcs13j4sonhjosopvh8rskke8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.code',
  );
}
